server:
  port : 3000
spring:
  main:
    web-application-type: reactive
  profiles:
    active: "prod"
---
spring:
  config:
    activate:
      on-profile: "h2"
  r2dbc:
    url: r2dbc:h2:file:///./tmp/test-database
    username: sa
    password: password
  flyway:
    url: jdbc:h2:file:./tmp/test-database
    locations: classpath:db-schema/
logging:
  level:
    io.r2dbc.*: DEBUG
---
spring:
  config:
    activate:
      on-profile: "dev"
  devtools:
    restart:
      enabled: true
      poll-interval: 5s