server:
  port : 3000
spring:
  main:
    web-application-type: reactive
  profiles:
    active: "prod"
---
spring:
  config:
    activate:
      on-profile: "prod"
---
spring:
  config:
    activate:
      on-profile: "dev"
  devtools:
    restart:
      enabled: true
      poll-interval: 5s